workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 120       # build duration in minutes (min 1, max 120)
    scripts:
      - git clone https://github.com/whiveio/whive-cpuminer-mc-yespower.git
      - cd whive-cpuminer-mc-yespower
      - ./build.sh
